### ISSUE TITLE
Folder reorganisation

### ISSUE THREAD

**Issue by limo1996** [limo1996/SAT-Solver#14]
We have too much folders in main folder. After Mondays presentation we should move all tests to common test folder, rename python_wrapper to scrips, move randomCNF to scripts.

**Comment by ebhardjan** [comment]
sounds good
The randomCNF script that is currently used has been already moved to the python_wrapper folder.
The randomCNF folder can be remove entirely.

**Comment by ebhardjan** [comment]
done in commit f96d4f1
