### ISSUE TITLE
Fix glitch in master worker communication

### ISSUE THREAD

**Issue by ebhardjan** [limo1996/SAT-Solver#15]
As discussed we should iprobe on a different tag.
The exception that I planted seems to be triggered in a couple of cases (13 times out of 840 executions).
Here's the output file from euler:
[lsf.o52407426](https://github.com/limo1996/SAT-Solver/files/1443964/lsf.o52407426.txt)

**Comment by limo1996** [comment]
We shall see whether glitch occurs in stealing scheduler. Because all small tests pass locally..

**Comment by limo1996** [comment]
Fixed by @ebhardjan . Tested on ton of cnfs. Done.
