### ISSUE TITLE
Identify cnfs in the plots

### ISSUE THREAD

**Issue by ebhardjan** [limo1996/SAT-Solver#18]
We should add an option to the plotting script to add numbers to identify formulas.

An idea on how this might look like:
https://stackoverflow.com/questions/14432557/matplotlib-scatter-plot-with-different-text-at-each-data-point

We should add a command line option to the plotting script that enables the numbers.
For command line option parsing one could use [the click python package](http://click.pocoo.org/5/), example usage is in main.py.

**Comment by ZiweiHuang94** [comment]
thank you for the explanation and resource. Hi, I already looked into it a bit. have some questions on plotter.py. See you in the lecture.
