### ISSUE TITLE
Move encoding and parsing of variables from worker to CNF

### ISSUE THREAD

**Issue by limo1996** [limo1996/SAT-Solver#2]
Jan, I think it would be better to move encoding and parsing of formula to CNF class so I can reuse it in Master class (I need to parse final formula and print it). I will push in few minutes data class named State that basically hold array of unsigned ints and its size + getter and setter. 

Your methods can looks like:
State CNF::encode();     //cnf will encode itself to State object

CNF cnf = new CNF(State state);   // cnf will parse itself from State object
// ---- or -----
CNF cnf = new CNF();
cnf.parse(State state);

What do you think about that?

**Comment by ebhardjan** [comment]
Sounds good.
I think "Model" would be a better name (since that's what it's called in this context) but otherwise I agree.

**Comment by limo1996** [comment]
Yeah. I will rename it to model and then you can merge branches and use the class

**Comment by limo1996** [comment]
Not necessary... Partially done...
