### ISSUE TITLE
More test cases!

### ISSUE THREAD

**Issue by ebhardjan** [limo1996/SAT-Solver#8]
We need more test-cases!
Small ones and also large ones.
We should store them in the repository such that everyone can run the same tests.

2 things:
1. just generate a lot of them (I would say 100 of size (number of variables) 10, 30, 50, 100, 200 at least)
2. change the names of the test files such that we know how "large" these formulas are (useful for evaluation)

**Comment by ZiweiHuang94** [comment]
now the names of the test files show number of variables and clauses, do you mean also add the number of examples? or should change the FOLDER name from "examples" to "examples_n_var_n_clau_n_ex"?

**Comment by ZiweiHuang94** [comment]
now the test files show the number of variables and the number of clauses. Do you mean also need to add the total number of examples?

**Comment by ebhardjan** [comment]
number of variables and clauses should be fine

**Comment by ZiweiHuang94** [comment]
I update Cnf generator code. For clear use, "generateCnf.py" is for normal formula generation without considering the probability of sat. "testCnfPro.py" will generate exact example sets with 0.5 sat (with large parameters it can be time-consuming to get probability to 0.5).

**Comment by ebhardjan** [comment]
Random generator is there with guarantees on the probability of sat/unsat.
Keep in mind that it can take some time to generate the formulas...
