### ISSUE TITLE
Runtime performance measurements on euler

### ISSUE THREAD

**Issue by ebhardjan** [limo1996/SAT-Solver#9]
We should store some runtime measurements in files on euler.
Such that one can then manually download them, run a script and get a nice plot (x-axis: size of formula i.e. number of variables, y-axis: runtime)
There are 3 changes necessary as far as I can see:

1. add information to how large randomly generated formulas are to the file names (overlaps with #8 )
2. measure runtime in parallel_main.cpp and store it in a file
3. write a script that given such files can create the plots

Additionally we should have far more and far larger formulas! -> #8

**Comment by ZiweiHuang94** [comment]
I can take this one. If I got stuck, I will let you know.

**Comment by ZiweiHuang94** [comment]
I am working on this. already add timestamp in parallel_main.cpp. however, it does not write the time to a file. I am trying to figure it out.

**Comment by ebhardjan** [comment]
done.
